#!/bin/bash

# Script to fetch Pikachu data from the Pokémon API

API_URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

curl -sSf "$API_URL" -o "$OUTPUT_FILE" 2>>"$ERROR_FILE"
if [ $? -ne 0 ]; then
  echo "Failed to fetch data from $API_URL" >> "$ERROR_FILE"
  exit 1
fi